### PR TITLE
Linux implementation using iwlist.

### PR DESCRIPTION
**Pull request by skovsgaard**
Please review carefully as I may have overlooked issues (or struggled too hard to avoid using regex for this).

The obvious problem is that `iwlist` itself attempts to print lines, creating an ugly but pretty much harmless side effect when run in iex.

### CODE REVIEW

**Comment by gausby** [comment]
Cool.

I got some issues with the test data I got from a friend though. The ssid seems to be wrapped in quotes. I don't know if this is normal behaviour, but the ssid becomes \"something.something\", which I assume is incorrect; we might have to strip those quotes.

And I think we need to strip white-spaces from the mac address.

And I might have to change the `ht` value in the %Wifi.BaseStation{} struct to default to `nil`.

Thanks for the pull request!

**Comment by gausby** [comment]
It seems to work with my data if I change the struct in gather_fields/1 to

``` elixir
%Wifi.BaseStation{
  ssid: get_field(cell_lines, "ESSID:") |> ssid_format,
  mac: get_field(cell_lines, "Address:") |> mac_format,
  rssi: get_field(cell_lines, "Signal level=") |> rssi_format,
  channel: get_field(cell_lines, "Channel:"),
  security: get_security(cell_lines)
}
```

…and adding these helper functions:

``` elixir
  defp mac_format(mac_field) do
    mac_field
    |> String.strip
  end

  defp ssid_format(ssid_field) do
    ssid_field
    |> String.replace("\"", "")
  end
```

Edit: `ssid_field |> String.strip(?")` could also be used to strip the quotes, but it borks up the syntax highlighting in my editor :-/

**Comment by skovsgaard** [comment]
I added the helpers and redid the struct. It seems to work now.

**Comment by gausby** [comment]
Awesome; could I ask you to rebase the commits into one?; then I'll merge it :)

**Comment by skovsgaard** [comment]
Okay, all changes are now in ecf73f8.

**Comment by gausby** [comment]
fixes #1

**Pull request merged**
